### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ionox0** [ionox0/Vimeo#2]
### TODO
- [ ] Tests
- [ ] gzip
- [ ] static caching
- [ ] favicon
- [x] Borders
- [ ] Mobile support
- [ ] Cross browser
- [ ] Router, routes
- [x] Polyfill for Promise
- [x] Urlencoded routes
- [ ] More Vimeo endpoints
- [x] Consistent templates/styles/views naming
- [ ] Leverage JSONP callback
- [ ] Ternary operator jshint error...
- [ ] Unimplemented Grunt tasks
- [x] Display video info (sidebar view)
- [ ] Animate List View (tray open/close)
- [ ] Display channel info (sidebar view)
- [ ] Extend models/views from base class
- [ ] Constructor pattern, private vars
- [x] Xhr cross-browser polyfill / $.ajax
